let Menu = {};
import Accordion_Animated_Icon from './Accordion_Animated_Icon.svelte';
import Accordion from "./Accordion.svelte";
import Accordion_Animated from "./Accordion_Animated.svelte";
import Bottom_Navigation from "./Bottom_Navigation.svelte";
import Bottom_Nav_Border_Links from "./Bottom_Nav_Border_Links.svelte";
import Breadcrumb from "./Breadcrumb.svelte";
import Centered_Menu_Link from "./Centered_Menu_Link.svelte";
import Dropup from "./Dropup.svelte";
import Equal_width_Menu_Links from "./Equal_width_Menu_Links.svelte";
import Fixed_Sidebar from "./Fixed_Sidebar.svelte";
import Full_Fixed_Sidebar from "./Full_Fixed_Sidebar.svelte";
import Horizontal_Scroll_Menu from "./Horizontal_Scroll_Menu.svelte";
import Hover_Dropdown from "./Hover_Dropdown.svelte";
import Hover_Sidebar_Buttons from "./Hover_Sidebar_Buttons.svelte";
import Mega_Menu from "./Mega_Menu.svelte";
import Menu_Three_Lines_Icon_Animated from "./Menu_Three_Lines_Icon_Animated.svelte";
import Menu_Three_Lines_Icon from "./Menu_Three_Lines_Icon.svelte";
import Navbar_On_Image from "./Navbar_On_Image.svelte";
import Pagination from "./Pagination.svelte";
import Responsive_Sidebar from "./Responsive_Sidebar.svelte";
import Right_Aligned_Menu_Buttons from "./Right_Aligned_Menu_Buttons.svelte";
import Search_Bar from "./Search_Bar.svelte";
import Subnav from "./Subnav.svelte";
import Top_Nav from "./Top_Nav.svelte";
import Top_Fixed_Menu from "./Top_Fixed_Menu.svelte";
import Vertical_Menu from "./Vertical_Menu.svelte";
import Vertical_Scroll_Menu from "./Vertical_Scroll_Menu.svelte";
Menu.Accordion = Accordion;
Menu.Accordion_Animated = Accordion_Animated;
Menu.Bottom_Navigation = Bottom_Navigation;
Menu.Bottom_Nav_Border_Links = Bottom_Nav_Border_Links;
Menu.Breadcrumb = Breadcrumb;
Menu.Centered_Menu_Link = Centered_Menu_Link;
Menu.Dropup = Dropup;
Menu.Equal_width_Menu_Links = Equal_width_Menu_Links;
Menu.Fixed_Sidebar = Fixed_Sidebar;
Menu.Full_Fixed_Sidebar = Full_Fixed_Sidebar;
Menu.Horizontal_Scroll_Menu = Horizontal_Scroll_Menu;
Menu.Hover_Dropdown = Hover_Dropdown;
Menu.Hover_Sidebar_Buttons = Hover_Sidebar_Buttons;
Menu.Mega_Menu = Mega_Menu;
Menu.Menu_Three_Lines_Icon_Animated = Menu_Three_Lines_Icon_Animated;
Menu.Menu_Three_Lines_Icon = Menu_Three_Lines_Icon;
Menu.Navbar_On_Image = Navbar_On_Image;
Menu.Pagination = Pagination;
Menu.Responsive_Sidebar = Responsive_Sidebar;
Menu.Right_Aligned_Menu_Buttons = Right_Aligned_Menu_Buttons;
Menu.Search_Bar = Search_Bar;
Menu.Subnav = Subnav;
Menu.Top_Nav = Top_Nav;
Menu.Top_Fixed_Menu = Top_Fixed_Menu;
Menu.Vertical_Menu = Vertical_Menu;
Menu.Vertical_Scroll_Menu = Vertical_Scroll_Menu;
Menu.Accordion_Animated_Icon = Accordion_Animated_Icon;
export default Menu;